### ISSUE TITLE
how use is correct code in Fragment viewmode observe

### ISSUE THREAD

**Issue by rogergcc** [rohitjakhar/mvvm_template_kotlin#4]
in viewmodel
```
fun getData() {
        viewModelScope.launch(Dispatchers.IO) {
            dataRepo.getData()
        }
    }
```
    
  I Fragment .observe not working. I want a example of use it with recycler /adapter
  
  i saw another repo like work that this but here dont know how code it
```
  when
   is Resource.Loading -> {
   is Resource.Success -> {
   is Resource.Failure -> {
```

**Comment by rohitjakhar** [comment]
in view model you can use live data or flow(state flow or shared flow) whatever you like.
I will also add some example of recycleview and adapter soon.
